### ISSUE TITLE
Run scripts aren't scalable or readable

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/FixCache#29]
The run scripts that you're using aren't a very good solution to the problem.
1. They don't scale, because every repo is going to need a new script. That's a pain.
2. They aren't readable, because it's not clear what the command-line arguments (or their values) represent.
3. They are specific to our own database, so arguably shouldn't be in the Git repository anyway.

As it is, this isn't deployable at other places.

Suggestion:
Make one script with multiple goals. Each goal is a separate project. Each project has clearly named variables indicating what each value does. You could also have a "build all" task that builds everything.

You could implement this easily using something like Rake (or make if you know that stuff). With Rake, you would have separate tasks for each project, which then feed their variables into one central task that actually runs Maven.

As we have Maven, putting the values in the `pom.xml` could also be possible for this, but it's tricky (I think [these instructions](http://www.mail-archive.com/user@mojo.codehaus.org/msg00151.html) would be what would have to happen).

**Comment by supertri** [comment]
Good point.

Since the run scripts were only there as wrappers around running FixCache directly from the command line so that we could have a record of the command lines we used in testing, we no longer need them.

I have removed them from the repository -- except for one RUN script which runs the --help flag so that it is clear how to use command line arguments.
